workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Fahman

    environment:
      vars:
        BUNDLE_ID: "com.fahman.fahman"
        APP_STORE_APPLE_ID: "6760599317"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files and CREATE if missing
        script: |
          app-store-connect fetch-signing-files "com.fahman.fahman" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Set Xcode to use profiles
        script: xcode-project use-profiles

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build IPA
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - Jameelalameer4@gmail.com
        notify:
          success: true
          failure: true
