// File generated by FlutterFire CLI.
// This file handles Firebase configuration for all platforms (Android, iOS, Web, macOS).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEKCrgVe8Nmr5h5HEH4UGbvL7v_6Yi9U',
    appId: '1:452105787522:android:b67ed6f8aee0fb246cfc9b',
    messagingSenderId: '452105787522',
    projectId: 'fahman-25241',
    storageBucket: 'fahman-25241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFo-Y_0AH7XNoRzDf993-JwoSRuKPb-EQ',
    appId: '1:452105787522:ios:177ed21c163bb2486cfc9b',
    messagingSenderId: '452105787522',
    projectId: 'fahman-25241',
    storageBucket: 'fahman-25241.firebasestorage.app',
    iosBundleId: 'com.fahman.fahman',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqb4PkoQxQHiiIMkMEBAnPrdIhTH_v68E',
    appId: '1:452105787522:web:6d1981d0f9456ea46cfc9b',
    messagingSenderId: '452105787522',
    projectId: 'fahman-25241',
    authDomain: 'fahman-25241.firebaseapp.com',
    storageBucket: 'fahman-25241.firebasestorage.app',
    measurementId: 'G-3LKWH28D6T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFo-Y_0AH7XNoRzDf993-JwoSRuKPb-EQ',
    appId: '1:452105787522:ios:f3c0aef2b7af767d6cfc9b',
    messagingSenderId: '452105787522',
    projectId: 'fahman-25241',
    storageBucket: 'fahman-25241.firebasestorage.app',
    iosBundleId: 'com.example.fahmanApp',
  );
}
